### ISSUE TITLE
A suggestion for add the "speed" in Realtime

### ISSUE THREAD

**Issue by Jerethon** [VvvfGeeks/VVVF-Simulator#10]
I'd suggest adding a "speed" field to the Realtime window, where the running speed would be derived from the information about `Frequency` , `gear ratio` , `wheel diameter` , etc., like this:

<img width="773" alt="Snipaste 2024-08-07 15 21 06" src="https://github.com/user-attachments/assets/0a4a7122-7f61-482e-85be-28f697e90c76">

The specific conversion formula is as follows:

> d - Wheel Diameter(d=860mm)
> f - Frequency(f=1hz)
> r - Motor rpm
> m - Gears of the motor(m=14)
> w - Gears of the Wheel(w=85)
> p - Pole pair / Polar Logarithm (p=2)
> v - Speed(km/h)

The first is about the connection between `motor rpm(r)` , `frequency(f)` , and `pole pairs(p)` 
> `r = 60f/p`

Then there is the connection between `speed(v)` , `motor rpm(r)` , `wheel diameter(d)` and `gear ratio(m/w)`
> `v = r * m / w * d * π * 0.00006`

So these two formulas can be simplified as follows:
> `v = 60 * f / p * m / w * d * π * 0.00006`

Let's bring in the exact values：
> `v = 60 * 1 / 2 * 14 / 85 * 840 * 3.1416 * 0.00006 ≈ 0.78237`

So The ratio of `speed` to `frequency` is about `0.782 : 1`

<img width="1218" alt="image" src="https://github.com/user-attachments/assets/27950a10-6d12-4752-824a-d2b22626ab74">
<img width="886" alt="image" src="https://github.com/user-attachments/assets/605460b5-2597-40f1-9052-a19028edc181">
<img width="944" alt="image" src="https://github.com/user-attachments/assets/6953902c-ba11-4bbf-b4d5-9f1f02efbaec">
<img width="683" alt="image" src="https://github.com/user-attachments/assets/ec333406-f9c1-4dd0-9937-8d123b723511">
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/fdb88049-fdca-4e83-b42f-1fc443509227">

**Comment by DKZ100-07072** [comment]
《Aug 7, 2024, 3:45 PM GMT+8》

**Comment by DKZ100-07072** [comment]
@Jerethon 《completed》

**Comment by Jerethon** [comment]
《《completed》》

---- Replied Message ----
| From | ***@***.***> |
| Date | 01/14/2025 11:51 |
| To | VvvfGeeks/VVVF-Simulator ***@***.***> |
| Cc | 02001 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [VvvfGeeks/VVVF-Simulator] A suggestion for add the "speed" in Realtime (Issue #10) |

@Jerethon 《completed》

**Comment by DKZ100-07072** [comment]
@Jerethon 《---- Replied Message ----
| From | ***@***.***> |
| Date | 01/14/2025 11:51 |
| To | VvvfGeeks/VVVF-Simulator ***@***.***> |
| Cc | 02001 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [VvvfGeeks/VVVF-Simulator] A suggestion for add the "speed" in Realtime (Issue [#10](https://github.com/VvvfGeeks/VVVF-Simulator/issues/10)) |

[@Jerethon](https://github.com/Jerethon) 《completed》

**Comment by DKZ100-07072** [comment]
@Jerethon 《![[图片]](https://github.com/user-attachments/assets/93555efc-1829-491d-9798-f36219c29f23 "[图片]")》
